### ISSUE TITLE
How does it handle circular schemas?

### ISSUE THREAD

**Issue by diegohaz** [gpbl/denormalizr#11]
I'm trying to test this, but I still can't figure out. Nor I know if it has performance issues. Can someone explain it?

**Comment by gpbl** [comment]
They are solved [by reference](https://github.com/gpbl/denormalizr/pull/2). Having some performance tests would be nice :)

**Comment by gpbl** [comment]
I'm closing this because inactive, please feel free to write back if need to reopen – thanks!
