### ISSUE TITLE
Update the README documentation

### ISSUE THREAD

**Issue by codeocelot** [gpbl/denormalizr#14]
First off, thanks for starting this project-- having a natural way to denormalize nested entities is definitely a helpful convenience. 

I notice the README documentation needs some minor updating, as what is currently there doesn't perform as expected. 

> `const article = normalized.entities.articles[0]; `

`articles` is an object indexed from 1, so `...articles['1']` to access the first article. 

Second, the last example doesn't return what it should. 

    const denormalized = denormalize([1], normalized.entities, articleSchema);

    denormalized === { '0': 1 }  // instead of [{id:1,title:'Some Article'...}]

**Comment by hirowatari** [comment]
Ran into this as well.  Is this a bug?  If not, what is the expected behaviour for `denormalize([1,2],...)`

**Comment by gpbl** [comment]
Could you write a test for this case? believe it's a problem in case the indexes are numbers and not strings.

**Comment by hirowatari** [comment]
gpbl, I don't think a test is necessary.  It seems this is the intended functionality, but example was just slightly wrong.

**Comment by gpbl** [comment]
@hirowatari fine then! Please open a PR with your change as I see it is already in your fork 👍
