### ISSUE TITLE
Feature request - support unpkg.com

### ISSUE THREAD

**Issue by dhlavaty** [gpbl/denormalizr#25]
Supporting unpkg.com is really useful when testing `denormalizr` in a JavaScript playgrounds like JSBin or CodePen.

I found this https://unpkg.com/denormalizr@0.3.4/ , but there is no UMD version of a library.

As an example, `normalizr` can be found on https://unpkg.com/normalizr@2.2.1/dist/normalizr.min.js

**Comment by gpbl** [comment]
It is there! https://unpkg.com/denormalizr
