### ISSUE TITLE
Lodash is getting duplicated in my build

### ISSUE THREAD

**Issue by just-boris** [gpbl/denormalizr#28]
I have `lodash` declared as a dependency in my app. The declaration is the following:

```
"lodash": "^4.15.0",
```

Also, I have found out that you are also depending on lodash, but with fixed version `4.16.3`. It causes that I have two `lodash` instances included into my webapp bundle `4.16.4` and `4.16.3`.

Do you mind to make lodash version more flexible? It follows semver rules, so I'd trust @jdalton, that here will be no breaking changes during minor releases.

**Comment by gpbl** [comment]
Sure yes, sorry for that! Would you mind to send a PR updating the dependencies' version with the caret?

**Comment by just-boris** [comment]
No problem, see #29
