### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by brabeji** [gpbl/denormalizr#3]
Hello and thank you for your awesome contribution!

Quick comment: I would like to denormalize array of entities like this:
```js
denormalize(arrayOfNormalizedEntities, entities, arrayOf(entitySchema))
```
It was my first try as it is analogical to
```js
normalize(arrayOfRawEntities, arrayOf(entitySchema))
```
What do you think?

**Comment by gpbl** [comment]
👋 @brabeji, would the following work for your case?

```js
arrayOfNormalizedEntities.map(entity => denormalize(entity, entities, entitySchema))
```

**Comment by brabeji** [comment]
It works for sure and I'm doing this already :) Just thought it would be nice to have considering `normalizr` api.

**Comment by gpbl** [comment]
Ha! Yes it would be a nice addition to support it :+1:

**Comment by brabeji** [comment]
Awesome!

**Comment by diegohaz** [comment]
+1

**Comment by jcarbo** [comment]
I've added support for this in #13 😄
