### ISSUE TITLE
Support normalizr 3.0

### ISSUE THREAD

**Issue by brunolemos** [gpbl/denormalizr#34]
Normalizr 3.0 has breaking API changes (see [docs](https://github.com/paularmstrong/normalizr/blob/c1cb33000deb3f7a42308c82f7448996818d0f01/docs/api.md) and [changelog](https://github.com/paularmstrong/normalizr/blob/b4ad95f3c19484341407c1ccee94e4bab79f7091/CHANGELOG.md)).
I migrated my app to it just to realize `denormalizr` didn't work.

EDIT: Submitted the pull request #35 to fix it :)

**Comment by brunolemos** [comment]
Created the pull request #35 to fix it :)

**Comment by gpbl** [comment]
Released as v0.5.0!

**Comment by brunolemos** [comment]
@gpbl thanks!
