### ISSUE TITLE
denormalize isn't working with normalizr 3.2.1

### ISSUE THREAD

**Issue by saitonakamura** [gpbl/denormalizr#37]
I'm trying to go through tutorial, but i'm stuck since denormalize simply isn't working and, instead of array of denormalized articles gives me this `{ '0': 1, '1': 2 }`

[REPRO is here, remix the project and see the logs](https://gomix.com/#!/project/faithful-butterfly)

**Comment by gpbl** [comment]
@saitonakamura please upgrade to v0.5.0 (just published) – it should work. Thanks!

https://gomix.com/#!/project/different-stew

**Comment by saitonakamura** [comment]
Wow, thanks a lot for such an astonishing speed!)
