### ISSUE TITLE
Deprecating this module 

### ISSUE THREAD

**Issue by gpbl** [gpbl/denormalizr#39]
Normalizr 3.2+ has built-in denormalization support, so this package [will be deprecated](https://github.com/gpbl/denormalizr/pull/35#issuecomment-279118985) as soon as https://github.com/paularmstrong/normalizr/pull/238 is closed and released.

A big thanks to the [contributors](https://github.com/gpbl/denormalizr/graphs/contributors) which helped to improve this library and to @paularmstrong for adding this feature to normalizr! ❤️

**Comment by diegohaz** [comment]
Thank you for your work on this, @gpbl 
This community is awesome.
