### ISSUE TITLE
Null should denormalize to null

### ISSUE THREAD

**Issue by andrewdodd** [gpbl/denormalizr#4]
First, thanks for the library. I was getting pretty tired of denormalising!

I found that when denormalising attributes that are `null` they are returned as empty objects, `{}`, instead of `null`.

I can get around this, I just thought I would see if it is deliberate or accidental.

**Comment by gpbl** [comment]
I've published this lib since I'm using it and I was hoping for some help and debug :sweat_smile: so many thanks for reporting this! 

I've never met such case, and I guess you are right: `null` attributes should stay `null`.

**Comment by andrewdodd** [comment]
I checked out the code have run the tests you wrote. It appears to denormalise `null` correctly. I'm guessing the bug must be on my end somewhere.

I'm going to close this for now. Thanks.
