### ISSUE TITLE
why is the second argument to denormalize required?

### ISSUE THREAD

**Issue by arunkjn** [gpbl/denormalizr#8]
Just wondering what is the need for the second argument that is supplied with list of all entities. Isnt it possible to denormalize a single entity given a schema?

**Comment by gpbl** [comment]
The reason behind denormalizr is to denormalize an entity containing references to other entities. This can't happen without passing the other entities to it.

**Comment by gpbl** [comment]
@arunkjn I think your question was answered. Feel free to write back if needed, thanks!
